const portfolio = [
  {
    cardClass: 'card1',
    cardTitle: 'Tonic',
    cardDesktopImage: './img/dec1.png',
    cardMobileImage: './img/SnapshootPortfolio(1).png',
    company: 'CANOPY',
    job: 'Back End Dev',
    year: '2015',
    cardInfo: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    technologies: ['html', 'css', 'javascript', 'github', 'ruby', 'bootstrap'],
    buttonText: 'See Project',
    modalInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry.',
    modalSeeButtonText: 'See Live',
    modalSeeButtonIcon: '',
    modalSourceButtonText: 'See Source',
    modalSourceButtonIcon: '',
  },
  {
    cardClass: 'working-cards',
    cardTitle: 'Multi-Post Stories',
    cardDesktopImage: './img/Dec2.png',
    cardMobileImage: './img/Snapshoot.png',
    company: 'CANOPY',
    job: 'Back End Dev',
    year: '2015',
    cardInfo: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    technologies: ['html', 'css', 'javascript', 'github', 'ruby', 'bootstrap'],
    buttonText: 'See More',
    modalInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry.',
    modalSeeButtonText: 'See Live',
    modalSeeButtonIcon: '',
    modalSourceButtonText: 'See Source',
    modalSourceButtonIcon: '',
  },
  {
    cardClass: 'works-card card3',
    cardTitle: 'Tonic',
    cardDesktopImage: 'img/Snapshoot-Portfolio3.png',
    cardMobileImage: 'img/Snapshoot-Portfolio-Mobile3.png',
    company: 'CANOPY',
    job: 'Back End Dev',
    year: '2015',
    cardInfo: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    technologies: ['html', 'css', 'javascript', 'github', 'ruby', 'bootstrap'],
    buttonText: 'See More',
    modalInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry.',
    modalSeeButtonText: 'See Live',
    modalSeeButtonIcon: '',
    modalSourceButtonText: 'See Source',
    modalSourceButtonIcon: '',
  },
  {
    cardClass: 'works-card card4 card-reverse',
    cardTitle: 'Multi-Post Stories',
    cardDesktopImage: 'img/Snapshoot-Portfolio4.png',
    cardMobileImage: 'img/Snapshoot-Portfolio-Mobile4.png',
    company: 'CANOPY',
    job: 'Back End Dev',
    year: '2015',
    cardInfo: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    technologies: ['html', 'css', 'javascript', 'github', 'ruby', 'bootstrap'],
    buttonText: 'See More',
    modalInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry.',
    modalSeeButtonText: 'See Live',
    modalSeeButtonIcon: '',
    modalSourceButtonText: 'See Source',
    modalSourceButtonIcon: '',
  },
];